config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 1000 }
  validates :status, presence: true, length: { maximum: 10 }, inclusion: { in: %w[未着手 進行中 完了] }
  validates :priority, length: { maximum: 10 }, inclusion: { in: ['高', '中', '低', '', nil] }

  scope :search, lambda { |search_params|
    return if search_params.blank?

    title_like(search_params[:title])
      .status_is(search_params[:status])
  }
  scope :title_like, ->(title) { where('title LIKE ?', "%#{title}%") if title.present? }
  scope :status_is, ->(status) { where(status: status) if status.present? }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @search_params = task_search_params
    @tasks = Task.search(@search_params).includes(:user)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task['user_id'] = 1 # ユーザーのログイン機能を作成していないので、ひとまず1で登録
    if @task.save
      redirect_to root_path, notice: '新しいタスクを作成しました'
    else
      flash.now[:alert] = 'タスクの作成ができませんでした'
      render new_task_path
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task.id), notice: 'タスクを更新しました'
    else
      flash.now[:alert] = 'タスクの更新ができませんでした'
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to root_path, notice: 'タスクを削除しました'
    else
      flash.now[:alert] = 'タスクの削除ができませんでした'
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :status, :priority, :deadline)
  end

  def task_search_params
    params.fetch(:search, params).permit(:title, :description, :status, :priority, :deadline)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= content_for?(:html_title) ? yield(:html_title) : 'RailsTraining' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="notifications">
    <% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
    <% end %>
  </div>
  <main>
    <%= yield %>
  </main>
</body>

</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task) do |form| %>
<p>
  <%= form.label :title, 'タイトル' %><br />
  <%= form.text_field :title, size: 27, maxlength: 100, required: true, id: 'form_title' %>
</p>
<p>
  <%= form.label :description, '説明' %><br />
  <%= form.text_area :description, size: '26x3', maxlength: 1000, id: 'form_description' %>
</p>
<p>
  <%= form.label :status, 'ステータス' %><br />
  <%= form.select :status, [['未着手', '未着手'], ['進行中', '進行中'], ['完了', '完了']], {prompt: 'タスクの状態'}, {id: 'form_status'} %>
</p>
<p>
  <%= form.label :priority, '優先度' %><br />
  <%= form.select :priority, [['高', '高'], ['中', '中'], ['低', '低']], {prompt: '優先度'}, {id: 'form_priority'} %>
</p>
<p>
  <%= form.label :deadline, '期限' %><br />
  <%= form.datetime_field :deadline, id: 'form_deadline' %>
</p>
<p>
  <%= form.submit text, id: 'form_submit' %>
</p>
<% end %>

app/views/tasks/edit.html.erb
<% content_for(:html_title) {'タスクの編集'} %>

<h1>タスクの編集</h1>
<p><%= button_to '戻る', 'javascript:history.back()', {method: :get} %></p>
<%= render partial: 'form', locals: {task: @task, text: '編集'} %>

app/views/tasks/index.html.erb
<% content_for(:html_title) {'タスクの一覧'} %>

<h1>タスクの一覧</h1>

<div>
  <%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <p>
    <%= form.label :title, 'タイトル' %>
    <%= form.text_field :title, value: @search_params[:title] %>
  </p>
  <p>
    <%= form.label :status, 'ステータス' %>
    <%= form.select :status, [['未着手', '未着手'], ['進行中', '進行中'], ['完了', '完了']], {prompt: 'タスクの状態'} %>
    <%= form.submit '検索' %>
  </p>
  <% end %>
</div>

<p><%= button_to '新規登録', {controller: 'tasks', action: 'new'}, {method: :get, id: 'new_button'} %></p>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>タスク名</th>
      <th>ユーザー名</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>期限</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.title %></td>
      <td><%= task.user.name %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= task.deadline %></td>
      <td><%= button_to '詳細', task_path(task.id), {method: :get} %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<% content_for(:html_title) {'タスクの新規登録'} %>

<h1>タスクの新規登録</h1>
<p><%= button_to '戻る', 'javascript:history.back()', {method: :get} %></p>
<%= render partial: 'form', locals: {task: @task, text: '新規登録'} %>

app/views/tasks/show.html.erb
<% content_for(:html_title) {'タスクの詳細'} %>

<h1>タスクの詳細</h1>

<p><%= button_to '戻る', 'javascript:history.back()', {method: :get} %></p>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>タスク名</th>
      <th>詳細</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>期限</th>
      <th>作成日</th>
      <th>更新日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task.id %></td>
      <td><%= @task.title %></td>
      <td><%= @task.description %></td>
      <td><%= @task.status %></td>
      <td><%= @task.priority %></td>
      <td><%= @task.deadline %></td>
      <td><%= @task.created_at %></td>
      <td><%= @task.updated_at %></td>
    </tr>
  </tbody>
</table>

<p>
<table>
  <tr>
    <td>
      <%= button_to '削除', "/tasks/#{@task.id}", {method: :delete, id: 'delete_button', data: {confirm: 'タスクを削除しても良いですか？'}} %>
    </td>
    <td>
      <%= button_to '編集', edit_task_path(@task.id), {method: :get, id: 'edit_button'} %>
    </td>
  </tr>
</table>
</p>